# Generated by Django 5.1.4 on 2025-01-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('guruh', models.IntegerField()),
                ('kurs', models.CharField(choices=[('Back-End', 'Back-End'), ('Front-End', 'Front-End'), ('Design', 'Design')], max_length=15)),
            ],
        ),
    ]
